resources:
- name: ConcourseTest
  type: git
  source:
    uri: https://github.com/SJTsai/ConcourseTest.git
    branch: master

jobs:
- name: ConcourseTest-run-tests
  plan:
  - get: ConcourseTest
    trigger: true
  - task: test-ConcourseTest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: rubygem/ambient-xcode
          tag: "latest"
      run:
        path: sh
        args:
        - -exc
        - |
          cd ConcourseTest
          gem install fastlane
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          fastlane test
      inputs:
      - name: ConcourseTest